# Generated by Django 3.1 on 2021-09-27 06:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAddon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classid', models.CharField(max_length=128)),
                ('instanceid', models.CharField(max_length=128)),
                ('assetid', models.CharField(max_length=128)),
                ('float', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('tradable', models.BooleanField(default=True)),
                ('inspect_url', models.TextField()),
                ('is_listed', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('is_listed',),
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('market_hash_name', models.CharField(max_length=255, unique=True)),
                ('icon_url', models.TextField(blank=True, null=True)),
                ('icon_url_large', models.TextField(blank=True, null=True)),
                ('type', models.CharField(max_length=64)),
                ('sub_type', models.CharField(blank=True, max_length=64, null=True)),
                ('weapon_type', models.CharField(blank=True, max_length=64, null=True)),
                ('exterior', models.CharField(blank=True, max_length=64, null=True)),
                ('rarity', models.CharField(blank=True, max_length=64, null=True)),
                ('rarity_color', models.CharField(blank=True, max_length=64, null=True)),
                ('stattrak', models.BooleanField(null=True)),
                ('souvenir', models.BooleanField(null=True)),
                ('tournament', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('date_listed', models.DateTimeField(auto_now_add=True)),
                ('purpose', models.CharField(choices=[('TRADE', 'TRADE'), ('SELL', 'SELL'), ('AUCTION', 'AUCTION')], default='TRADE', max_length=32)),
                ('inventory', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listed', to='csgo.inventoryitem')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_listed',),
            },
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='addons',
            field=models.ManyToManyField(blank=True, through='csgo.InventoryAddon', to='csgo.Item'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_inventory', to='csgo.item'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryaddon',
            name='addon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csgo.item'),
        ),
        migrations.AddField(
            model_name='inventoryaddon',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csgo.inventoryitem'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='csgo.listing')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(fields=('assetid', 'owner'), name='unique_item'),
        ),
    ]
