# Generated by Django 3.2.6 on 2021-09-01 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
                ('iconurl', models.CharField(blank=True, max_length=5080, null=True)),
                ('type', models.CharField(blank=True, max_length=128, null=True)),
                ('weapon_type', models.CharField(blank=True, max_length=128, null=True)),
                ('gun_type', models.CharField(blank=True, max_length=128, null=True)),
                ('exterior', models.CharField(blank=True, max_length=128, null=True)),
                ('rarity', models.CharField(blank=True, max_length=128, null=True)),
                ('rarity_color', models.CharField(blank=True, max_length=128, null=True)),
                ('stattrak', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('float', models.FloatField()),
                ('price', models.PositiveBigIntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csgo.item')),
            ],
        ),
    ]
