# Generated by Django 3.1 on 2021-09-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.AddField(
            model_name='cart',
            name='item',
            field=models.ManyToManyField(related_name='cart_items', to='csgo.Listing'),
        ),
    ]
