# Generated by Django 3.1 on 2022-01-22 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='addons',
        ),
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='csgo.inventoryitem')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='csgo.item')),
            ],
        ),
    ]
