# Generated by Django 3.1 on 2022-01-23 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0002_auto_20220122_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transaction', to='csgo.listing'),
        ),
    ]
