# Generated by Django 3.2.6 on 2021-09-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='addons_test',
            field=models.ManyToManyField(related_name='listings', to='csgo.Item'),
        ),
    ]
