# Generated by Django 3.1 on 2021-09-23 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0002_auto_20210921_2242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ('is_listed',)},
        ),
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ('-date_created',)},
        ),
        migrations.RemoveField(
            model_name='listing',
            name='assetid',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='classid',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='inspect_url',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='instanceid',
        ),
    ]
