# Generated by Django 3.1 on 2021-09-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0002_auto_20210927_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={},
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='paintindex',
            field=models.CharField(default='ad', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='paintseed',
            field=models.CharField(default='ad', max_length=16),
            preserve_default=False,
        ),
    ]
