# Generated by Django 3.1 on 2021-09-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0003_auto_20210923_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
