# Generated by Django 3.1 on 2022-01-26 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0003_auto_20220123_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='csgo.listing'),
        ),
    ]
