# Generated by Django 3.1 on 2021-09-29 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0004_auto_20210929_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csgo.cart')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csgo.listing')),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='item',
        ),
        migrations.AddField(
            model_name='cart',
            name='item',
            field=models.ManyToManyField(related_name='cart_items', through='csgo.CartItem', to='csgo.Listing'),
        ),
    ]
