# Generated by Django 3.1 on 2022-01-26 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0004_auto_20220126_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csgo.listing'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('owner', 'listing'), name='unique cartitem'),
        ),
    ]
