# Generated by Django 3.2.6 on 2021-09-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0004_auto_20210901_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='addons',
            field=models.ManyToManyField(null=True, related_name='addons', to='csgo.Item'),
        ),
    ]
