# Generated by Django 3.2.6 on 2021-09-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0005_alter_listing_addons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='addons',
            field=models.ManyToManyField(blank=True, null=True, related_name='addons', to='csgo.Item'),
        ),
    ]
