# Generated by Django 3.1 on 2021-09-29 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('csgo', '0005_auto_20210929_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('ESEWA', 'ESEWA'), ('KHALTI', 'KHALTI'), ('BANK', 'BANK')], max_length=64)),
                ('state', models.CharField(choices=[('PAYMENT PENDING', 'PAYMENT PENDING'), ('PAYMENT COMPLETE', 'PAYMENT COMPLETE'), ('TRADE SENT', 'TRADE SENT'), ('TRADE ACCEPTED', 'TRADE ACCEPTED'), ('FUNDS TRANSFERRED', 'FUNDS TRANSFERRED'), ('TRANSACTION COMPLETE', 'TRANSACTION COMPLETE'), ('BUYER ERROR', 'BUYER ERROR'), ('SELLER ERROR', 'SELLER ERROR')], max_length=64)),
                ('trade_sent_screenshot', models.ImageField(upload_to='')),
                ('trade_recv_screenshot', models.ImageField(upload_to='')),
                ('state_last_changed', models.DateTimeField(auto_now=True)),
                ('transaction_started', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='csgo.listing')),
            ],
        ),
    ]
