# Generated by Django 3.1 on 2022-01-29 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0005_auto_20220126_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallettransaction',
            old_name='user',
            new_name='owner',
        ),
    ]
