# Generated by Django 3.1 on 2021-09-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0006_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='in_inventory',
            field=models.BooleanField(default=True),
        ),
    ]
