# Generated by Django 4.0.3 on 2022-03-15 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0007_alter_addon_id_alter_cartitem_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='inventory',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='csgo.inventoryitem'),
        ),
    ]
