# Generated by Django 3.1 on 2021-10-01 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0007_inventoryitem_in_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='csgo.listing'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('ESEWA', 'ESEWA'), ('KHALTI', 'KHALTI'), ('BANK', 'BANK')], default='ESEWA', max_length=64),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trade_recv_screenshot',
            field=models.ImageField(upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trade_sent_screenshot',
            field=models.ImageField(upload_to='uploads'),
        ),
    ]
