# Generated by Django 3.1 on 2021-10-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0008_auto_20211001_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='defindex',
            field=models.CharField(default='1348', max_length=16),
            preserve_default=False,
        ),
    ]
