# Generated by Django 4.0.3 on 2022-03-20 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0008_alter_listing_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='khalti',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='owner',
        ),
        migrations.DeleteModel(
            name='KhaltiTransaction',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='WalletTransaction',
        ),
    ]
