# Generated by Django 3.1 on 2021-09-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0008_auto_20210908_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='iconurl',
        ),
        migrations.AddField(
            model_name='item',
            name='icon_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='icon_url_large',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='market_hash_name',
            field=models.CharField(default='asd', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='exterior',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='item',
            name='gun_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='item',
            name='rarity',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='item',
            name='rarity_color',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='item',
            name='stattrak',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='item',
            name='weapon_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('name', 'exterior', 'gun_type', 'stattrak'), name='unique_item'),
        ),
    ]
