# Generated by Django 3.1 on 2021-10-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0009_inventoryitem_defindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
