# Generated by Django 3.1 on 2021-09-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0009_auto_20210909_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='icon_url_large',
            field=models.TextField(blank=True, null=True),
        ),
    ]
