# Generated by Django 3.1 on 2021-09-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0010_auto_20210909_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
