# Generated by Django 3.1 on 2021-09-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0011_auto_20210909_1313'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='item',
            name='unique_item',
        ),
        migrations.AlterField(
            model_name='item',
            name='market_hash_name',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
