# Generated by Django 3.1 on 2021-10-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0011_auto_20211006_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='purpose',
            field=models.CharField(choices=[('TRADE', 'TRADE'), ('SELL', 'SELL'), ('AUCTION', 'AUCTION')], default='SELL', max_length=32),
        ),
    ]
