# Generated by Django 3.1 on 2021-09-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0012_auto_20210909_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='exterior',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='gun_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='rarity',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='rarity_color',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='weapon_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
