# Generated by Django 3.1 on 2021-10-22 08:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0012_auto_20211008_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
