# Generated by Django 3.1 on 2021-09-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0013_auto_20210909_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='market_hash_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
