# Generated by Django 3.1 on 2021-12-10 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0013_listing_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='payment_method',
        ),
    ]
