# Generated by Django 3.1 on 2021-09-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0014_auto_20210909_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='gun_type',
            new_name='sub_type',
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(max_length=64),
        ),
    ]
