# Generated by Django 3.1 on 2021-12-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0014_remove_transaction_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=models.CharField(choices=[('1', 'PAYMENT PENDING'), ('2', 'PAYMENT COMPLETE'), ('3', 'TRADE SENT'), ('4', 'TRADE ACCEPTED'), ('5', 'FUNDS TRANSFERRED'), ('6', 'TRANSACTION COMPLETE'), ('100', 'BUYER ERROR'), ('99', 'SELLER ERROR')], max_length=64),
        ),
    ]
