# Generated by Django 3.1 on 2021-09-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0015_auto_20210909_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='souvenir',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='tournament',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
