# Generated by Django 3.1 on 2021-09-10 17:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0016_auto_20210909_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingAddon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5)])),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csgo.item')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csgo.listing')),
            ],
        ),
    ]
