# Generated by Django 3.1 on 2021-12-12 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0017_khaltitransaction_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='khalti',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='csgo.khaltitransaction'),
        ),
    ]
