# Generated by Django 3.1 on 2021-09-10 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0018_auto_20210910_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='csgo.item'),
        ),
    ]
