# Generated by Django 3.1 on 2021-09-12 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0019_auto_20210911_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csgo.item'),
        ),
    ]
