# Generated by Django 3.1 on 2021-09-15 13:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('csgo', '0020_auto_20210912_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classid', models.CharField(max_length=128)),
                ('instanceid', models.CharField(max_length=128)),
                ('assetid', models.CharField(max_length=128)),
                ('float', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('tradable', models.BooleanField(default=True)),
                ('inspect_url', models.URLField()),
                ('addons', models.ManyToManyField(blank=True, to='csgo.Item')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='csgo.item')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
