# Generated by Django 3.1 on 2021-09-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0022_auto_20210916_1712'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(fields=('classid', 'instanceid', 'assetid'), name='unique_item'),
        ),
    ]
