# Generated by Django 3.1 on 2021-09-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0023_auto_20210916_1724'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventoryitem',
            name='unique_item',
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(fields=('classid', 'instanceid', 'assetid', 'inspect_url'), name='unique_item'),
        ),
    ]
