# Generated by Django 3.1 on 2021-09-16 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0025_auto_20210916_1727'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventoryitem',
            name='unique_item',
        ),
    ]
