# Generated by Django 3.1 on 2021-09-16 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0026_auto_20210916_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_inventory', to='csgo.item'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(fields=('assetid', 'owner'), name='unique_item'),
        ),
    ]
