# Generated by Django 3.1 on 2021-09-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0027_auto_20210916_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='assetid',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='classid',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='inspect_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='instanceid',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='tradable',
            field=models.BooleanField(default=True),
        ),
    ]
