# Generated by Django 3.1 on 2021-09-17 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0028_auto_20210916_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='inspect_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='inspect_url',
            field=models.TextField(null=True),
        ),
    ]
