# Generated by Django 3.1 on 2021-09-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0029_auto_20210917_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='inspect_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.UniqueConstraint(fields=('owner', 'assetid'), name='unique_inventory_listing'),
        ),
    ]
