# Generated by Django 3.1 on 2021-09-18 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0032_inventoryitem_is_listed'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='inventory',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='csgo.inventoryitem'),
        ),
    ]
