# Generated by Django 3.1 on 2021-09-19 16:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0033_listing_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
