# Generated by Django 3.1 on 2021-09-20 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0035_auto_20210919_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='assetid',
            field=models.CharField(blank=True, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='classid',
            field=models.CharField(blank=True, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='instanceid',
            field=models.CharField(blank=True, max_length=128, unique=True),
        ),
    ]
