# Generated by Django 3.1 on 2021-09-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0037_auto_20210920_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='exterior',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='item',
            name='icon_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='icon_url_large',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='rarity',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='item',
            name='rarity_color',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='item',
            name='sub_type',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='item',
            name='weapon_type',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
