# Generated by Django 4.0.3 on 2022-03-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_room_alter_room_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='group',
            field=models.BooleanField(default=False),
        ),
    ]
