# Generated by Django 3.1 on 2022-01-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_credit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='steamid64',
            field=models.CharField(default='76561198323043075', max_length=17, unique=True),
            preserve_default=False,
        ),
    ]
