# Generated by Django 4.0.3 on 2022-03-20 16:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_profile_id_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocked_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
